### ISSUE TITLE
Thank you for your production

### ISSUE THREAD

**Issue by Demisemo** [Lunat1q/ScreenAccess#2]
Will you update this project recently?

**Comment by Lunat1q** [comment]
What do you mean? It's updated for the latest version of the game and should work just fine.

**Comment by Demisemo** [comment]
Currently available
Looking forward to adding Peacekeeper, Wingman Weapon

Have Discord to follow up with new information?

**Comment by Lunat1q** [comment]
Ehm... Peacekeeper and Wingman disabled on purpose since they doesn't have any recoil to mitigate.

**Comment by Lunat1q** [comment]
No discord so far, see no reason for now, you can use forum thread mentioned in readme.

**Comment by Demisemo** [comment]
1920x1080 Frameless window
Is this possible to play recoil?

**Comment by Lunat1q** [comment]
What do you mean? It was made for such settings.
Did you even try it?

**Comment by Demisemo** [comment]
Tried, the effect is not obvious
Recoil will go up

**Comment by Demisemo** [comment]
![image](https://user-images.githubusercontent.com/18625503/60797323-a31e7680-a1a1-11e9-8e5e-717f544db27c.png)
![image](https://user-images.githubusercontent.com/18625503/60797571-17f1b080-a1a2-11e9-9aef-359311b8cdb4.png)

Not open before RELOAD
https://youtu.be/ajkCFAv7uBk
https://youtu.be/JBecK2v9RPo

**Comment by Lunat1q** [comment]
If you expect zero recoil accuracy - I will never do it.
1. It's way too dangerous and detectable
2. It gives way too much of advance

Every shot here compensate average recoil + some randomization to prevent detection and reports by the players.

Closing the case, please proceed to the forum thread for future assistance.

**Comment by Demisemo** [comment]
I see what you mean.
This feature is a bit random
Better gaming experience after use
Mainly Kill the enemy
Not killing the enemy easily

Will be added in the future
1.Increase footsteps
2.Find enemy locations faster

I am not happy to use scripts、hack
The game experience is terrible

**Comment by Lunat1q** [comment]
Not a clue what did you mean in the last sentence. 
Anyway, goodluck.
