### ISSUE TITLE
Will this script work in languages other than English? (OCR)

### ISSUE THREAD

**Issue by DadyaVasyaXD** [Lunat1q/ScreenAccess#3]
For example, I have Russian Language and some weapons have Russian names.

UPD. Только узнал что ты русский, изменять тему не стал.

**Comment by DadyaVasyaXD** [comment]
Проблема решилась сама собой.

**Comment by Lunat1q** [comment]
You can modify the source code to make it work for RU or any other locale (just add a map for weapon type to expected recognized word). But i'm not qutie sure that OCR is trained for any language other than EN.
